// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phcsogbxgkmeskpowoba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBoY3NvZ2J4Z2ttZXNrcG93b2JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNDM4MzcsImV4cCI6MjA2NTkxOTgzN30.-3Yb_jHiMb5lC1dmDkRBsvGRoOcNL3Ebl_jq2ml6rGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);