
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phcsogbxgkmeskpowoba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBoY3NvZ2J4Z2ttZXNrcG93b2JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNDM4MzcsImV4cCI6MjA2NTkxOTgzN30.-3Yb_jHiMb5lC1dmDkRBsvGRoOcNL3Ebl_jq2ml6rGM";

// Rileva se siamo su mobile per configurare timeout più lunghi
const isMobile = () => {
  if (typeof navigator === 'undefined') return false;
  return /Mobi|Android/i.test(navigator.userAgent);
};

// Configurazione ottimizzata per mobile
const supabaseOptions = {
  db: {
    schema: 'public' as const,
  },
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  },
  realtime: {
    // Timeout più lunghi e riconnessione automatica più robusta
    timeout: isMobile() ? 60000 : 45000, // Timeout più lunghi per evitare disconnessioni
    heartbeatIntervalMs: isMobile() ? 20000 : 15000, // Heartbeat meno frequenti per stabilità
    reconnectAfterMs: (tries: number) => {
      const baseDelay = isMobile() ? 3000 : 2000;
      return Math.min(tries * baseDelay, 15000); // Riconnessione più graduale
    },
    // Abilita riconnessione automatica robusta
    params: {
      eventsPerSecond: 10
    }
  },
  global: {
    headers: {
      'X-Client-Info': `supabase-js-web/2.50.0${isMobile() ? '-mobile' : ''}`
    }
  }
};

console.log('🔧 Supabase client configurato per:', {
  isMobile: isMobile(),
  realtimeTimeout: supabaseOptions.realtime.timeout,
  heartbeatInterval: supabaseOptions.realtime.heartbeatIntervalMs
});

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, supabaseOptions);
