// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzpypkxhhllaeixjuerw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6cHlwa3hoaGxsYWVpeGp1ZXJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzIzNTEsImV4cCI6MjA2NTkwODM1MX0.icoldzVuyYyLCdC5J1KCTHMOuemhhrK36Fc-EetZTho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);